from knote.knote_helpers import date_parse, time_parse

def test_date_parse():
    ret = date_parse("1999-08-12")
    assert (ret.year == 1999) and (ret.month == 8) and (ret.day == 12)
    ret = date_parse("TRASH")
    assert not(ret)
    ret = date_parse("2000-13-01")
    assert not(ret)
    ret = date_parse("2000-12-32")
    assert not(ret)
    ret = date_parse("2000-12-12-1")
    assert not(ret)
    ret = date_parse("2000-12")
    assert not(ret)

def test_time_parse():
    ret = time_parse("10:20")
    assert (ret.hour == 10) and (ret.minute == 20)
    ret = time_parse("10:20AM")
    assert (ret.hour == 10) and (ret.minute == 20)
    ret = time_parse("10:20PM")
    assert (ret.hour == 22) and (ret.minute == 20)
    ret = time_parse("20:20")
    assert (ret.hour == 20) and (ret.minute == 20)
    ret = time_parse("20:20AM")
    assert (ret.hour == 20) and (ret.minute == 20)
    ret = time_parse("20:20PM")
    assert not(ret)
    ret = time_parse("20:61")
    assert not(ret)
    ret = time_parse("25:59")
    assert not(ret)
    ret = time_parse("TRASH")
    assert not(ret)
